CREATE FULLTEXT CATALOG LogsFullTextForLogText
WITH ACCENT_SENSITIVITY = OFF

CREATE FULLTEXT INDEX ON Logs(LogText)
KEY INDEX PK_Logs
ON LogsFullTextForLogText
WITH CHANGE_TRACKING AUTO

CHECKPOINT; DBCC DROPCLEANBUFFERS;

SELECT * FROM Logs
WHERE LogText LIKE '% 1256789'

CHECKPOINT; DBCC DROPCLEANBUFFERS;

SELECT * FROM Logs
WHERE CONTAINS(LogText,'1256789')